version: 2.1
jobs:
  job1:
    machine: true
    steps:
      - run:
          name: Job 1
          command: |
            echo "Job 1 is running at tag: " + $CIRCLE_TAG
  check:
    machine: true
    steps:
      - run: docker-compose -v
      - run: docker -v
#      - slack/status:
#        mentions: USERID1,USERID2
#        webhook: webhook
  scan:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  build:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/app
    steps:
      - checkout
      - run: mvn clean install
      - run: echo "Build step finished"
      - run: ls -la
      - persist_to_workspace:
          root: ~/app
          paths:
            - target
      - run: ls -laR ~/app
  test:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run: java -cp target/jb-hello-world-maven-0.1.0.jar hello.HelloWorld
      - run: docker-compose -v
      - run: docker -v
#orbs:
#  sonarcloud: sonarsource/sonarcloud@1.0.0
#  slack: circleci/slack@3.4.1
workflows:
  version: 2
  flow1:
    jobs:
      - job1:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
#      - check
#      - scan:
#          context: SonarCloud
#      - build
#      - test:
#         requires:
#           - build
#      
