version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
        - checkout
        - run: mvn clean install
        - run: echo "Build step finished"
  test:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
        - run: java -cp target/jb-hello-world-maven-0.1.0.jar hello.HelloWorld
workflows:
  version: 2
  flow1:
    jobs:
      - build
      - test
      